DROP TABLE IF EXISTS TRADE;  
CREATE TABLE TRADE (  
trade_id INT AUTO_INCREMENT  PRIMARY KEY,  
seller VARCHAR(50) NOT NULL,
buyer VARCHAR(50) NOT NULL,
stock VARCHAR(50) NOT NULL,
price INT(8) NOT NULL,
trade_date  VARCHAR(50) NOT NULL
);  
DROP TABLE IF EXISTS ORDERS;  
CREATE TABLE ORDERS (  
order_id INT AUTO_INCREMENT  PRIMARY KEY,  
party VARCHAR(50) NOT NULL,
category VARCHAR(50) NOT NULL,
stock VARCHAR(50) NOT NULL,  
price INT(8) NOT NULL  
);  